// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsLott.DAL;

#nullable disable

namespace NewsLott.DAL.Migrations
{
    [DbContext(typeof(NewsLottDbContext))]
    [Migration("20230814233853_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsLott.Entidades.CompaniaDeLoteria", b =>
                {
                    b.Property<string>("IdCompaniaDeLoteria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCompania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCompaniaDeLoteria");

                    b.ToTable("companiaDeLoteria");

                    b.HasData(
                        new
                        {
                            IdCompaniaDeLoteria = "nacional",
                            NombreCompania = "Nacional"
                        },
                        new
                        {
                            IdCompaniaDeLoteria = "leidsa",
                            NombreCompania = "Leidsa"
                        },
                        new
                        {
                            IdCompaniaDeLoteria = "real",
                            NombreCompania = "Real"
                        });
                });

            modelBuilder.Entity("NewsLott.Entidades.Loteria", b =>
                {
                    b.Property<string>("IdLoteria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCompaniaDeLoteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreLoteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoteria");

                    b.HasIndex("IdCompaniaDeLoteria");

                    b.ToTable("loteria");

                    b.HasData(
                        new
                        {
                            IdLoteria = "gana_mas",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8246),
                            IdCompaniaDeLoteria = "nacional",
                            NombreLoteria = "Gana Mas"
                        },
                        new
                        {
                            IdLoteria = "loteria_nacional",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8261),
                            IdCompaniaDeLoteria = "nacional",
                            NombreLoteria = "Loteria Nacional"
                        },
                        new
                        {
                            IdLoteria = "juega_+_pega_+",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8262),
                            IdCompaniaDeLoteria = "nacional",
                            NombreLoteria = "Juega + Pega +"
                        },
                        new
                        {
                            IdLoteria = "pega_3_mas",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8264),
                            IdCompaniaDeLoteria = "leidsa",
                            NombreLoteria = "Pega 3 Mas"
                        },
                        new
                        {
                            IdLoteria = "loto_pool",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8265),
                            IdCompaniaDeLoteria = "leidsa",
                            NombreLoteria = "Loto Pool"
                        },
                        new
                        {
                            IdLoteria = "super_kino_tv",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8268),
                            IdCompaniaDeLoteria = "leidsa",
                            NombreLoteria = "Super Kino TV"
                        },
                        new
                        {
                            IdLoteria = "quiniela_leidsa",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8270),
                            IdCompaniaDeLoteria = "leidsa",
                            NombreLoteria = "Quiniela Leidsa"
                        },
                        new
                        {
                            IdLoteria = "loto_loto_mas",
                            FechaRegistro = new DateTime(2023, 8, 14, 19, 38, 53, 630, DateTimeKind.Local).AddTicks(8271),
                            IdCompaniaDeLoteria = "leidsa",
                            NombreLoteria = "Loto Mas"
                        });
                });

            modelBuilder.Entity("NewsLott.Entidades.ResultadoDeLoteria", b =>
                {
                    b.Property<string>("IdResultadoDeLoteria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaResultado")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdLoteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumerosPremiados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResultadoDeLoteria");

                    b.HasIndex("IdLoteria");

                    b.ToTable("resultadoDeLoteria");
                });

            modelBuilder.Entity("NewsLott.Entidades.Loteria", b =>
                {
                    b.HasOne("NewsLott.Entidades.CompaniaDeLoteria", "CompaniaDeLoteria")
                        .WithMany("Loterias")
                        .HasForeignKey("IdCompaniaDeLoteria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompaniaDeLoteria");
                });

            modelBuilder.Entity("NewsLott.Entidades.ResultadoDeLoteria", b =>
                {
                    b.HasOne("NewsLott.Entidades.Loteria", "Loteria")
                        .WithMany("ResultadoDeLoterias")
                        .HasForeignKey("IdLoteria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loteria");
                });

            modelBuilder.Entity("NewsLott.Entidades.CompaniaDeLoteria", b =>
                {
                    b.Navigation("Loterias");
                });

            modelBuilder.Entity("NewsLott.Entidades.Loteria", b =>
                {
                    b.Navigation("ResultadoDeLoterias");
                });
#pragma warning restore 612, 618
        }
    }
}
